### ISSUE TITLE
Redux store data not used in React tutorial 'Data' chapter

### ISSUE THREAD

**Issue by rich-TIA** [chromaui/learnstorybook.com#131]
I followed through the chapter [Wire In Data](https://www.learnstorybook.com/react/en/data/) on wiring in data. I couldn't help notice that the data in the store did not appear to be used in the final code, or show up in Storybook.

Indeed it doesn't even appear in the screenshots which accompany the chapter and subsequent chapters.

I know it is possible to make this happen because I am currently the client on a live SB project which is using a data store to display data.

Not suggesting this is an error but perhaps an explanation would be helpful.

**Comment by jonniebigodes** [comment]
@rich-TIA i'm inclined to believe that the chapter in question demonstrates the capabilities of storybook, it demonstrates that you can hook up a datasource, like in this case redux store and test it in isolation so to speak. Also i'm inclined to believe that the reason that the code does not move onto other chapters is because it's meant to be kept simple and don't try to "muddy the waters"(pardon the bad pun)

**Comment by rich-TIA** [comment]
Thank you @jonniebigodes . That makes sense and I'm comfortable with the results of the Data chapter not flowing into subsequent ones. However, I think it would add to the power of the tutorial were the data store as wired have a material effect on the stories on display. Apart from anything else, it would ensure students know they have taken all the right steps. As it is, I now have no idea whether my attempt worked - it compiles and throws no exceptions, but it has no effect - and I also have no idea how to make it work for real.

*Full disclosure* I am completely new to this react/redux game, and perhaps this tutorial is aimed more at those who have some sort of clue what's going on :)

**Comment by domyen** [comment]
That's a good point @rich-TIA. As @jonniebigodes mentioned, the goal of the tutorial is to teach people how to build and compose UI components. Avoiding deep dives into data is intentional because it's a complex ever-changing topic (plus there are more comprehensive guides out there). We're trying to cover how a dev _might_ manage data without prescribing a best practice.

**Comment by rich-TIA** [comment]
Fair enough and thanks for your time guys. I'll close this issue now.
