### ISSUE TITLE
SDS: MDX causes chromatic test error

### ISSUE THREAD

**Issue by chiangs** [chromaui/learnstorybook.com#174]
Going through the Design System tutorial, after adding the `Intro.stories.mdx` file, the build fails on the chromatic test on CircleCI...builds fine locally.
![code](https://user-images.githubusercontent.com/10984593/66461915-4a999680-ea7a-11e9-8819-cfbdc4624abe.png)
![code](https://user-images.githubusercontent.com/10984593/66461941-5ab17600-ea7a-11e9-93f4-616bd918037f.png)
![code](https://user-images.githubusercontent.com/10984593/66462061-98160380-ea7a-11e9-8efd-6fa5037a8982.png)
<img width="1153" alt="Screen Shot 2019-10-09 at 09 54 37" src="https://user-images.githubusercontent.com/10984593/66462183-d7445480-ea7a-11e9-9161-c0ac586c3d3a.png">

**Comment by jpmarra** [comment]
@chiangs Try clearing your CircleCI cache. update the `v1` to `v2` in the `config.yml`under `restore_cache` and `save_cache` like so:
![Screen Shot 2019-10-09 at 11 04 12 AM](https://user-images.githubusercontent.com/22504731/66493752-96e9d400-ea84-11e9-987e-3673d4aab193.png)

This is likely due to the timing of SB updates from `5.2.1` to `5.2.3`. Even though your current local env is building correctly, its possible that the cached packages in CircleCI are still mismatched.

**Comment by chiangs** [comment]
@jpmarra did not make a difference for me, still same error in the build.

**Comment by horacioh** [comment]
maybe this is related to #165 ?

**Comment by chiangs** [comment]
This fixed it [link](https://github.com/storybookjs/storybook/issues/8345#issuecomment-539739617)
