### ISSUE TITLE
Incorrect use of prepare script & missing @babel/cli dependency

### ISSUE THREAD

**Issue by jpmarra** [chromaui/learnstorybook.com#176]
## Babel Issue
While working through the Distribute instructions, I ran into a babel issue when the package was building after install (unfortunately I didn't get a screenshot of this before I fixed it). It was an `unknown option` error to the build script `"BABEL_ENV=production babel src -d dist"`.

After looking through the example code base, I realized that `@babel/cli` was a dependency. I added it to my own package and published. This totally fixed the issue. 

**PROPOSED CHANGE**:
Add instructions around adding `@babel/cli` as a dependency.

## Prepare issue
_I ran through this issue within the two example repos, as well as my personal repo_

I realized that the example repo is using the `prepare` script from npm which is run BEFORE the package is packed and published. This causes an issue wherever the build is run because Babel is going to include the import statements with the wrong direct path.  
_Screenshot of issue:_
![Screen Shot 2019-10-09 at 12 17 12 PM](https://user-images.githubusercontent.com/22504731/66501737-f4385200-ea91-11e9-9c67-738152601358.png)

Which then hits the following error once the stories are imported (for each file):
![Screen Shot 2019-10-09 at 12 34 16 PM](https://user-images.githubusercontent.com/22504731/66502226-d8817b80-ea92-11e9-8d12-5019329897b6.png)

This example has the build context from within the users local build, but when publishing through `auto`, the build is run in the context of CircleCI causing the direct path to be something like `home/circleci/node_modules...`

**PROPOSED CHANGE**:
Changing the prepare script to `postinstall` solves this issue as it only runs the build within the correct context (within the node_modules directory of the app in which its installed)

There currently is no documentation surrounding the need for a build to run once the package is installed to create the `dist` folder within the node module. I think there should be some documentation around having the correct script run after the package is installed (with `postinstall`).

I also noticed that after installing the example package created by @tmeasday that the index.js file had incorrect paths to the components. It seems to be fixed in the repo, but probably needs to be published with the updated chage.

**Comment by tmeasday** [comment]
> PROPOSED CHANGE:
> Add instructions around adding @babel/cli as a dependency.

I think maybe you just missed this one?

<img width="840" alt="image" src="https://user-images.githubusercontent.com/132554/66533794-e224e500-eb5f-11e9-9d5f-dd9dd849ddac.png">

> I realized that the example repo is using the prepare script from npm which is run BEFORE the package is packed and published. This causes an issue wherever the build is run because Babel is going to include the import statements with the wrong direct path.

Whoa, this is super surprising! Why is babel not just importing from `@babel/runtime` (which should end up being  dependency of our published design system), but instead importing from the installed location of `@babel/runtime`. That's not right.

> I also noticed that after installing the example package created by @tmeasday that the index.js file had incorrect paths to the components. It seems to be fixed in the repo, but probably needs to be published with the updated chage.

This is actually just a mistake I made due to moving stuff around. I didn't actually want anyone to install my test package but I guess given I included screenshots they probably would. I'll release a new version once we resolve the above.

**Comment by jpmarra** [comment]
> I think maybe you just missed this one?

Totally missed that step! My bad.

> Whoa, this is super surprising! Why is babel not just importing from @babel/runtime (which should end up being dependency of our published design system), but instead importing from the installed location of @babel/runtime? That's not right.

Definitely seems like `@babel/runtime` shouldbe handling these imports. 🤷‍♂  Whats the benefit of using `prepare` here over `postinstall`?

**Comment by tmeasday** [comment]
> Whats the benefit of using prepare here over postinstall?

I think `prepare` runs the build process before `npm publish`, whereas `postinstall` runs it after the user installs the package. Usually people just publish the contents of their `dist` so the user doesn't need to install the `devDependencies` (require for build) in order to use the package (and to avoid a bunch of CPU cycles ;) )

**Comment by jonniebigodes** [comment]
@tmeasday are you ok with closing this? It seems a bit irrelevant now with the latest updates for the tutorial.

**Comment by tmeasday** [comment]
Seems like we recently solved a similar issue with a newer version of babel in any case ;)
