### ISSUE TITLE
Can't install with Angular project

### ISSUE THREAD

**Issue by jonnysmith1981** [chromaui/learnstorybook.com#223]
I have tried both the "Quick" and "Slow"-start instructions but in both cases the installation fails with: `Error: Could not find a default project in your Angular workspace. Add a project and re-run the installation.`
Using Angular 8.3.6

**Comment by geromegrignon** [comment]
As stated, you need a default project into your workspace.
Did you create your workspace with Angular CLI using the `--createApplication= false` option?

Then you may add one using `ng generate application <application name>`.

**Comment by jonnysmith1981** [comment]
This is the structure of my workspace (created by the Angular CLI):
![image](https://user-images.githubusercontent.com/8254912/69643197-ded7b100-105a-11ea-944e-e4f214ebe881.png)

**Comment by geromegrignon** [comment]
I tried to reproduce your issue :

* `npm install -g @angular/cli@8.3.6`
* `ng new projectName`
* `npx -p @storybook/cli sb init --type angular`

I was able to install Storybook correctly.
The only way to reproduce your issue was creating a workspace without a default project.

May you add a link to a repo with your project to inspect it?

**Comment by jonnysmith1981** [comment]
Sorry for the delay in responding. I started a new blank ng project and compared its angular.json with my own. My version was missing the `defaultProject` config and once I added that in I was able to install Storybook.
