### ISSUE TITLE
Customize Storybook layout

### ISSUE THREAD

**Issue by KrishnanSriram** [chromaui/learnstorybook.com#245]
Can we customize top left corner logo (Storybook image) and search bar for enterprise consumption?
<img width="210" alt="storybook" src="https://user-images.githubusercontent.com/5131690/71913726-151e4b00-3146-11ea-9d53-1b1e6a8c9b30.png">

**Comment by jonniebigodes** [comment]
@KrishnanSriram to the best of my knowledge and based on the documentation you can apply some styling to the layout of your Storybook, you can read up more about it [here](https://storybook.js.org/docs/configurations/theming/). That particular change you intend to do, i believe that it's probably not possible. I'll leave it to more knowledgeable people with Storybook to add a more detailed answer about this issue.

**Comment by domyen** [comment]
As @jonniebigodes mentioned, you can theme SB – checkout the theming docs. Here's a [cool theming example](https://reaviz.io/?path=/story/docs-intro--page) from the community. 

I'm going to close this now because it's not related to the tutorial. If you have further questions, try [our Discord chat](https://discord.gg/UUt2PJb) or the Storybook issue tracker. Thanks!

**Comment by jonniebigodes** [comment]
@domyen you forgot to actually close it 😉
