### ISSUE TITLE
Make framework and language chooser more discoverable

### ISSUE THREAD

**Issue by domyen** [chromaui/learnstorybook.com#270]
It's hard to find how to get to Angular or Vue tutorials. Requires some design.

Reported by Kai Roeder who maintains the SB Angular integration 🙏

**Comment by jonniebigodes** [comment]
We could start with making the icons in the landing page for each framework a link to each version of the tutorial. 
More specifically those
![lsb_change_1](https://user-images.githubusercontent.com/22988955/73383937-2f20f880-42c2-11ea-9cc6-77b6d649bd7b.png)

**Comment by domyen** [comment]
That is an awesome idea for that landing page.

For the tutorial sidebar, what do you think about separating the framework
and languages picker like so? That way folks can immediately see which
frameworks are available to them.
[image: image.png]

**Comment by tmeasday** [comment]
@domyen the image didn't work

**Comment by domyen** [comment]
![image](https://user-images.githubusercontent.com/263385/73467426-4f4bc880-4351-11ea-8faa-96da5e86a387.png)

**Comment by jonniebigodes** [comment]
@domyen @tmeasday @kylesuss you mean something like this:
![lsb_change_2](https://user-images.githubusercontent.com/22988955/73558823-daa98480-444b-11ea-8f41-d7d17b55ed7f.png)
![lsb_change_3](https://user-images.githubusercontent.com/22988955/73558825-daa98480-444b-11ea-9d50-a5588ea2d7d4.png)

I'm still taking a look at the styling and design system components used to fine tune this. So that's why the weird styling that is displayed, but is this what's invisioned?

**Comment by domyen** [comment]
This is awesome @jonniebigodes! Thanks a ton (and apologies for the lag 🙏). Will follow up in the draft PR.

**Comment by jonniebigodes** [comment]
@domyen no problem, no need to apologize, i know that you're probably hard at work, same as the rest of the team.

**Comment by jonniebigodes** [comment]
@domyen sorry for taking this long to merge this. Is now merged and with that i'm going to close this issue if you don't mind

**Comment by domyen** [comment]
Close away :)
