### ISSUE TITLE
minor mistake on Creating addons page

### ISSUE THREAD

**Issue by toshihidetagami** [chromaui/learnstorybook.com#280]
On Creating addons Page,

> We'll need to make a small change to the .babelrc file we created earlier. We need to add a reference to the @babel/preset-react package.

I followed this tutorial from the beginning, but I think there was no step to create babelrc file.

**Comment by jonniebigodes** [comment]
@toshihidetagami the documentation was correct up until recently, as the changes introduced with Storybook 5.3 alot has changed and that section was left a bit untouched. And for that i'm sorry as i was the person behind the rewording/restructuring of the said section.

 I'm currently doing some validations regarding this particular section so that it will benefits not only you but the rest of the community. And prevent possible misleadings.  I need to bring a minor issue to the attention of the Storybook team and see how to proceed from there.

Once again sorry for the misleading that was introduced by the oversight.

**Comment by jonniebigodes** [comment]
@toshihidetagami to provide you some additional context up until version 5.3, for instance with React, you were required to have a `.babelrc` file to allow Storybook to grab the stories correctly. It was covered in the guide.  And when i did the rewording of the said section of the tutorial it was matching correctly. When version 5.3 came into play it meant a lot of nice features one of which the simplification of the configuration and with that it meant the need for the `.babelrc` file became somewhat irrelevant. The create addons section was left untouched while i updated the remainder documentation to said version and during that process, test if everything was ok with the new version. Based on a recent conversation with one of the maintainers and the original author of the said section it seems that there still some work that needs to be done to said section. I'm going to bring to the attention the remainder of the maintainers of this repo on how we can best approach this situation and possibly offer you a solution.

**Comment by toshihidetagami** [comment]
Thank you so much for the detailed explanation. Because this problem will be covered in #284, I will close this issue.
