### ISSUE TITLE
React Typescript Examples missing

### ISSUE THREAD

**Issue by thisnamewasnottaken** [chromaui/learnstorybook.com#318]
The React/TypeScript examples are missing in Intro to Storybook.

**Comment by jonniebigodes** [comment]
@thisnamewasnottaken sorry for the delay in responding to your issue, I think that is by design, when the documentation was created it was intended to be approachable by a broader audience, to both newcomers and more advanced developers with this ecossystem. Newcomers to React will see a familiar codebase and developers more familiar with Typescript and React can use this and make the transition with relative ease. 

Don't know if you know, but in the official Storybook repo the examples contain a Storybook example with Typescript and React, more specifically [here](https://github.com/storybookjs/storybook/tree/next/examples/cra-ts-kitchen-sink) be advised they are using the latest beta version, so some edge cases might not be yet contemplated and fine tuned, with that some issues might arise. 

Feel free to provide feedback

**Comment by domyen** [comment]
Hey @thisnamewasnottaken, @jonniebigodes is correct. React TS is not something we're planning to do yet.
