### ISSUE TITLE
Some Tutorial Instructions Not working (Package Scoping and some other): Distribute

### ISSUE THREAD

**Issue by TamaraPK** [chromaui/learnstorybook.com#444]
Location: https://www.learnstorybook.com/design-systems-for-developers/react/en/distribute/

Publishing the project to npm will not work (as others have published the same project e.g. while doing this tutorial)

One has to use scoping:
https://docs.npmjs.com/about-scopes
https://docs.npmjs.com/creating-and-publishing-scoped-public-packages

Package Meta Data:
Had to change "yarn init" to
yarn init --scope=@npmusername

Publish:
Had to use the yarn version of "npm publish" with public access (otherwise I would get errors):
yarn publish --access=public

Release:
"yarn release" did not work. Gave ENEEDAUTH error (not authorized) although "yarn auto release" works fine. Had to use:
npm run release

Add package to app:
This did not work "yarn add -learnstorybook-design-system" (I did add my npm username). This worked:
yarn add @npmusername/learnstorybook-design-system

Note: sometimes the yarn command works sometimes the npm command works (e.g. in Publish and Release above). Not sure if this something wrong I did from my side. I have been following the tutorial as is.

I hope this is helpful!

**Comment by jonniebigodes** [comment]
@TamaraPK Closing this now and once again thank you for bringing this to our attention. The tutorial is now documenting how to use scoped packages to avoid issues with publishing. 

Regarding this:
> Publish:
Had to use the yarn version of "npm publish" with public access (otherwise I would get errors):
yarn publish --access=public

That is indeed a consideration that you have to factor in when publishing Scoped packages into the npm registry. 

Regarding this:
> Release:
"yarn release" did not work. Gave ENEEDAUTH error (not authorized) although "yarn auto release" works fine. Had to use:
npm run release

This is probably related to the auth flow, you'll have to authenticate first and then issue the command.
