### ISSUE TITLE
Error with CLI token

### ISSUE THREAD

**Issue by Zangetsu89** [chromaui/learnstorybook.com#477]
By adding the below section: 

# Workflow name
name: 'Chromatic Deployment'

# Event for the workflow
on: push

# List of jobs
jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - run: yarn
        #👇 Adds Chromatic as a step in the workflow
      - uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/svelte/en/deploy/ to obtain it
          projectToken: project-token
          token: ${{ secrets.GITHUB_TOKEN }}

I ran into an error and after looking into chromaui/action it seems that the error is in 'projectToken: project-token' which should be instead projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }} 
as well by adding the Chromatic token in secrets in gh.

**Comment by jonniebigodes** [comment]
@Zangetsu89 I'm currently working on some updates for the documentation and I've factored in your issue and with that polished the tutorial a bit to present a clearer idea of what you should do so that you or any other reader can basically copy and paste the code on your local environment and push it to a GH repo and get the Action working as it's meant.

Stay safe

**Comment by jonniebigodes** [comment]
@Zangetsu89 the documentation was updated to factor in your issue and provide a bit of clarity regarding GitHub secrets.

Thank you for opening up this issue. if You don't mind I'm going to close it as the pull request is going to be merged soon.


Feel free to open a new issue if you run into any problems with the tutorials.

Stay safe
