### ISSUE TITLE
Angular version of "simple component" chapter doesn't refer to argTypes.  

### ISSUE THREAD

**Issue by nagashimam** [chromaui/learnstorybook.com#487]
It's more of question than issue but the explanation of default export in [Angular version](https://github.com/chromaui/learnstorybook.com/blob/master/content/intro-to-storybook/angular/en/simple-component.md#get-setup) doesn't refer to argTypes while [React version](https://github.com/chromaui/learnstorybook.com/blob/master/content/intro-to-storybook/react/en/simple-component.md#get-setup) does("argTypes -- specify the args behavior in each story." ). Is it intentional?

If not I'll create a PR to add that line in React to Angular too, since that property can often be useful(e.g, when you deal with types of control).

**Comment by jonniebigodes** [comment]
@nagashimam first and foremost sorry for the confusion. The general rule of thumb for that portion of the documentation is:
- If the Task component's story has `argTypes` defined, (e.g., Vue, Svelte) then it's documented.
- Otherwise such as Angular and React, it doesn't it shouldn't.

In your case for Angular has the Task story has no `argTypes` defined. Then no need to mention them. Looking at my notes this change was introduced accidentally a while ago. I'm going to make a small pull request addressing this.

Thanks for letting us know.

Stay safe

**Comment by jonniebigodes** [comment]
@nagashimam thank you for the heads up and help to clarify the tutorial. As I've mentioned before a pull request is up to address the issue. And I saw that you already updated it in your translation 🙂

Stay safe
