### ISSUE TITLE
Run alongside vs separately

### ISSUE THREAD

**Issue by teekirol** [chromaui/learnstorybook.com#51]
In the Storybook official documentation, it says 

> Storybook runs outside of your app.

But in the intro of your guide, it says

> Storybook runs alongside your app in development mode.

Can you talk about this discrepancy?

**Comment by tmeasday** [comment]
Hi @teekirol- storybook runs as a separate process to your main application -- it serves on a different port (say localhost:6006 vs localhost:3000) and is started via a separate command. You only really run storybook in development -- it doesn't really make sense to run it in production.

So that's what is meant by both statements -- storybook is not "part" of your app (in that it doesn't run inside it), but you typically run it at the same time as your app ("alongside")

Does that answer your question?

**Comment by teekirol** [comment]
Yes it does, thank you.
