### ISSUE TITLE
Storybook with react-native doesn't load

### ISSUE THREAD

**Issue by Deltaxel** [chromaui/learnstorybook.com#538]
Hi all,

I followed the following tutorial https://storybook.js.org/tutorials/intro-to-storybook/react-native/en
There was no issues during installation. The step for `@storybook/addon-ondevice-actions` was not even needed as it is installed by default in current version.
However, when running `yarn storybook`, the editor doesn't load properly.
![image](https://user-images.githubusercontent.com/4036889/136818456-31111c7f-1aa0-40b4-b385-a4ff3057b5c4.png)

Is this a known issue? Is there a way to fix it?

**Comment by jonniebigodes** [comment]
@Deltaxel thanks for reaching out and let us know of your issue with the tutorial, we really appreciate it. To give you some context on this, the React Native version of the tutorial is in dire need of some TLC, we're well aware of it. In the near future, I'll be following up with the maintainer and see how far along he's progressed with the new release of Storybook for React Native and also implement a similar structure as the other versions of the tutorial so that you and any other React Native developers get a similar experience, without the need to "jump through hoops" to get started with Storybook. Once we've come up with a timeline and plan we'll be applying those changes and update the tutorial. With that out of the way, i would like to ask you something, what happens if you spin up the simulator first and then start Storybook? Are you able to see the stories being rendered? Let me know so that I can factor in this tiny but crucial piece of information. 

Have a fantastic day!

Stay safe

**Comment by jonniebigodes** [comment]
Closing this for now in favor of #608
