### ISSUE TITLE
Copy-paste is difficult with diff code blocks

### ISSUE THREAD

**Issue by ChrisCrossCrash** [chromaui/learnstorybook.com#585]
After working my way through the tutorials for a while now, I wanted to give some feedback regarding code blocks with diff sections. For example:

![image](https://user-images.githubusercontent.com/40023417/153710819-0416b609-fb8a-4f94-80f3-cbe658312f6b.png)

As you might imagine, it gets a bit annoying to have to delete the `+` on every line after copy and pasting. I've seen some other sites that take a different approach:

- [React docs](https://reactjs.org/docs/components-and-props.html#composing-components) - The changes have a different background color.
- [Gatbsy Docs](https://www.gatsbyjs.com/docs/tutorial/part-2/) - Different background color **and** a button to copy the code block.

Perhaps it would be better without the `+` signs?

**UPDATE**

Just FYI, after a little digging it looks like the styling comes from the [@storybook/design-system](https://github.com/storybookjs/design-system/blob/master/src/components/Highlight.tsx) dependency. I suppose it would need to change there?

**Comment by jonniebigodes** [comment]
@ChrisCrossCrash thanks for bringing this to our attention, we appreciate it and we're well aware of the case. As of now, it seems a bit of a "clunky" process (pardon the bad pun), me and the other maintainers have talked about this internally and we're looking into alternatives so that we can address this issue. Hopefully, we'll get something out soon and improve the DX not only for you but for other readers as well. Once we get something out I can loop you in for a bit of testing. Sounds good?

**Comment by ChrisCrossCrash** [comment]
Sounds good! Thanks for your consideration.

**Comment by DavidMorenoDev** [comment]
I had the same problem...Hope it gets changed! 😊

**Comment by jeffslofish** [comment]
I was so frustrated by the copy-paste issue with code-diff blocks, that I created #633. Enjoy!
