### ISSUE TITLE
Type annotations can only be used in TypeScript files.

### ISSUE THREAD

**Issue by kemalgencay** [chromaui/learnstorybook.com#611]
I am working on Storybook tutorial, while editing Task.js file I get the error in the title of this msg.
Any suggestions please
TIA
Regards

**Comment by jonniebigodes** [comment]
@kemalgencay hum...that's strange, could it be that you copied something from the tutorial and your code editor is mistakenly interpreting it incorrectly? Or could be something else?
Can you provide us with some additional context on your development environment so that it can be looked at?

Hope you have a great week.

Stay safe

**Comment by jonniebigodes** [comment]
Closing this issue for now. Let me know if you're still running into this issue and I'll gladly re-open it and continue to work with you on it until we find a suitable solution that helps you go through the tutorial without any issues.
