### ISSUE TITLE
Bug: Getting started step in "Storybook for React Native tutorial" does not work

### ISSUE THREAD

**Issue by Nautman** [chromaui/learnstorybook.com#617]
Hi, I have followed the instructions for [getting started in the Storybook for React Native tutorial](https://storybook.js.org/tutorials/intro-to-storybook/react-native/en/get-started/). Unfortunately, when I reach the step to run the storybook, it fails.

These are the errors

```
ERROR in ./storybook/addons.js
Module not found: Error: Can't resolve '@storybook/addon-actions/manager' in '/redacted/user/project/storybook'
 @ ./storybook/addons.js 1:0-41
 @ multi ./node_modules/@storybook/react-native-server/node_modules/@storybook/core/dist/server/common/polyfills.js ./storybook/addons.js ./node_modules/@storybook/react-native-server/dist/client/manager/index.js

ERROR in ./storybook/addons.js
Module not found: Error: Can't resolve '@storybook/addon-knobs/manager' in '/redacted/user/project/storybook'
 @ ./storybook/addons.js 1:80-119
 @ multi ./node_modules/@storybook/react-native-server/node_modules/@storybook/core/dist/server/common/polyfills.js ./storybook/addons.js ./node_modules/@storybook/react-native-server/dist/client/manager/index.js

ERROR in ./storybook/addons.js
Module not found: Error: Can't resolve '@storybook/addon-links/manager' in '/redacted/user/project/storybook'
 @ ./storybook/addons.js 1:41-80
 @ multi ./node_modules/@storybook/react-native-server/node_modules/@storybook/core/dist/server/common/polyfills.js ./storybook/addons.js ./node_modules/@storybook/react-native-server/dist/client/manager/index.js

```

I am very grateful for any help on how to set up Storybook for React Native. Please tell me if you need more information.

Thanks!

**Comment by jonniebigodes** [comment]
@Nautman, thanks for reaching out to us with your issue; we appreciate it. To give you a bit of context, this is not an issue with the tutorial itself but actually with the CLI, which has been fixed with the following [pull request](https://github.com/storybookjs/storybook/pull/18693). Hopefully, the fix will be released in a couple of days and should get you unblocked. 

I hope you don't mind, but I will close the issue. 

Let me know if the issue still persists, and I'll gladly follow up with you on it.

Have a great weekend.

Stay safe
