### ISSUE TITLE
Latest version of addon-knobs breaks tutorial

### ISSUE THREAD

**Issue by agrippanux** [chromaui/learnstorybook.com#63]
Hi

In following your excellent tutorial, I ran into a roadblock on the Addons section.  Doing `yarn add @storybook/addon-knobs` gives me the latest addon-knobs (v4.x), and that causes an "Accessing non-existent channel" error when going to Storybook.

After a comparing your code @ https://github.com/chromaui/learnstorybook-code/commit/f4d933#diff-f5db38d9ba5560598e902c026311b340, I updated my package.json to `"@storybook/addon-knobs": "^3.3.15"`, reinstalled, and everything worked fine.

**Comment by tmeasday** [comment]
Hi @agrippanux -- is it possible you started the tutorial before Storybook 4 was release (early last week)? If so I think the issue is just that you started with SB3.4 then installed the v4 knobs addon. 

I think Storybook should show a better error in such cases but I think this was just bad luck in your case! I'm glad you figured it out! The tutorial now has been updated to work with SB4, but as you noticed the source code we link to is still the 3.4 version
