### ISSUE TITLE
Vue tutorials

### ISSUE THREAD

**Issue by sosensible** [chromaui/learnstorybook.com#643]
The initial learn Storybook tutorial has some code issues with the Vuex code. I have a fix, but modern Vue standards are promoting Pinia over Vue. Pinia is the official upgrade for Vuex.

Lesson in focus: https://storybook.js.org/tutorials/intro-to-storybook/vue/en/data/

How do others think we should update this?

**Comment by jonniebigodes** [comment]
@sosensible thanks for opening up this issue. We appreciate it. Can you elaborate on the issues with the VueX code? If by that, you're referring to the fact that the store is not actually updated when setting up the interaction story but instead just logs it in the actions panel. I'm aware of this fact. That is actually due to how Vue hooks into Storybook. Also, I've been trying out Pinia, as it's now the spiritual successor for VueX, and still doing some testing with it.

Looking forward to hearing from you

**Comment by jonniebigodes** [comment]
With a recent pull request, the Vue edition of the tutorial was updated to feature Pinia as the default state management tool. This is the first update, and hopefully as Pinia grows, we'll be able to extend this feature, add more context, and take advantage of its features alongside Storybook. Should any issues arise, feel free to comment here.

**Comment by sosensible** [comment]
Awesome, Pinia does the same thing as Vuex. Well, it isn't as abstract so it does the good parts. LOL

**Comment by jonniebigodes** [comment]
Great to hear @sosensible, and I couldn't agree more with you. There's a bit of work still in terms of integration, but so far, it's been a great experience just to get it running and how little code is required to set up and access a store. Thank you very much for putting this on our radar, We appreciate it.
