### ISSUE TITLE
Not able to run tests in simple component chapter

### ISSUE THREAD

**Issue by LeadingLight** [chromaui/learnstorybook.com#65]
I am not able to run yarn test after setting up the .storybook/config.js file in the simple component chapter. 

The issue is that it won't find the require.context function that seems to be webpack specific.

```javascript
     TypeError: require.context is not a function
       2 | import '../src/index.css';
       3 |
     > 4 | const req = require.context('../src', true, /.stories.js$/);
         |                     ^
       5 |
```

**Comment by tmeasday** [comment]
Hi @LeadingLight, things are a little confusing here. Which version of the tutorial are you following?

The solution to this problem is using a babel plugin (see https://github.com/storybooks/storybook/tree/next/addons/storyshots/storyshots-core#configure-jest-to-work-with-webpacks-requirecontext) -- unfortunately CRA (the react version) doesn't support custom webpack configs, so we are kind of stuck here. I'm working on fixing it but it is moving slowly.

If you are doing the react version, I would suggest removing the `require.context` and manually `import`-ing all the `.stories` files for now.

**Comment by LeadingLight** [comment]
Ops, sorry for not providing more context.

Thanks for the explanation.
Yes, I am running the react version, so manual labour it is then :)

FYI I also had an issue with running the storybook after project creation.
I hade to run `yarn add @babel/plugin-syntax-jsx` before `yarn run storybook` would run successfully.
