### ISSUE TITLE
[React][Intro to Storybook] Add highlight to filenames and commands

### ISSUE THREAD

**Issue by Nischal2015** [chromaui/learnstorybook.com#667]
## Description
With this issue, the intent is to add highlights to filenames, folders, and commands for easy visibility.

**Example**
First, let’s create the task component and its accompanying story file: src/components/Task.js and src/components/Task.stories.js

## Solution
**Example**
First, let’s create the task component and its accompanying story file: `src/components/Task.js` and `src/components/Task.stories.js`

Adding backticks works in Github but not while rendering the HTML. The solution should probably be implemented in CSS styling.

## Contribution
I'm willing to create a PR to address this topic if accepted.

**Comment by jonniebigodes** [comment]
@Nischal2015, thanks for taking the time and effort to reach out to us with your proposed improvements. We appreciate it. If you're still willing to do this, let me know so that we can follow up on it. As I'm keen on seeing how you're willing to address it. Let me know if you have any questions or when the pull request is up. 

Looking forward to hearing from you.

Hope you have a great weekend.

Stay safe

**Comment by Nischal2015** [comment]
Thanks for the response.
I am willing to do this.

**Comment by jonniebigodes** [comment]
That's great to hear, and thank you for following up with me on this. As I've mentioned before looking forward to seeing this one materialized.

**Comment by Nischal2015** [comment]
Sure
