### ISSUE TITLE
exprect()ToBeInTheDocument throws a TypeScript error as if it didn't exist in @storybook/jest

### ISSUE THREAD

**Issue by santiagopuentep** [chromaui/learnstorybook.com#691]
The function works but TypeScript doesn't find the types for `jest-dom` functions in the `@storybook/jest` package.

**Comment by jonniebigodes** [comment]
@santiagopuentep, thanks for taking the time to reach out to us and opening this issue, I hope you don't take it the wrong way, but I'm going to close this, as this repository is for the tutorials themselves. With that in mind, can you do us a favour and open up an issue in the `@storybook/jest` repo detailing it so that we know it and address it as soon as possible?

I hope you have a great weekend.

Stay safe

**Comment by santiagopuentep** [comment]
Sorry, I posted here and I realized that it wasn't for code right after. I already posted at @storybook/jest.

**Comment by jonniebigodes** [comment]
Thanks for following up with me and opening up the issue on the `@storybook/jest` repo. Appreciate it 🙏
